using System.Data.SQLite;
using System.Text;
using System.Text.Json;

namespace AsperetaWeb
{
    /// <summary>
    /// Exports the game-data tables of the server database to www/wiki/data.js for the static
    /// wiki. The rows are written as System.Data.SQLite (the server's library) reads them: no joins,
    /// no defaults, no derived values;
    /// the wiki page decodes them in the browser. Only the tables listed here are read, so
    /// player, account and log tables never leave the database.
    /// </summary>
    public static class WikiExporter
    {
        public static readonly string[] Tables =
        {
            "item_templates",
            "npc_templates",
            "npc_drops",
            "npc_vendor_items",
            "npc_spawns",
            "spells",
            "spell_effects",
            "classes",
            "classes_levelup_spells",
            "maps",
            "map_required_items",
            "quests",
            "quest_requirements",
            "quest_rewards",
            "combinations",
            "combination_item_required",
            "combination_item_results",
            "item_titles",
            "item_surnames",
        };

        public static int Run(string dbPath, string outPath, string assetsDir, string singlePath)
        {
            if (!File.Exists(dbPath))
            {
                Console.Error.WriteLine($"Database not found: {Path.GetFullPath(dbPath)}");
                return 1;
            }

            var connection = new SQLiteConnectionStringBuilder
            {
                DataSource = dbPath,
                ReadOnly = true,
            };

            using var buffer = new MemoryStream();
            using (var json = new Utf8JsonWriter(buffer))
            using (var conn = new SQLiteConnection(connection.ToString()))
            {
                conn.Open();
                json.WriteStartObject();
                json.WriteNumber("version", 1);
                json.WriteString("generated", DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm 'UTC'"));
                json.WriteString("source", Path.GetFileName(dbPath));
                json.WriteStartObject("tables");

                foreach (string table in Tables)
                {
                    using var command = conn.CreateCommand();
                    command.CommandText = $"SELECT * FROM \"{table}\"";
                    SQLiteDataReader reader;
                    try
                    {
                        reader = command.ExecuteReader();
                    }
                    catch (SQLiteException e)
                    {
                        // An older database without one of the optional tables still exports.
                        Console.Error.WriteLine($"  {table}: skipped ({e.Message.Split('\n')[0].Trim()})");
                        continue;
                    }

                    using (reader)
                    {
                        json.WriteStartObject(table);
                        json.WriteStartArray("columns");
                        for (int i = 0; i < reader.FieldCount; i++) json.WriteStringValue(reader.GetName(i));
                        json.WriteEndArray();

                        json.WriteStartArray("rows");
                        int count = 0;
                        while (reader.Read())
                        {
                            json.WriteStartArray();
                            for (int i = 0; i < reader.FieldCount; i++) WriteValue(json, reader.GetValue(i));
                            json.WriteEndArray();
                            count++;
                        }
                        json.WriteEndArray();
                        json.WriteEndObject();
                        Console.WriteLine($"  {table}: {count} rows");
                    }
                }

                json.WriteEndObject();
                json.WriteEndObject();
            }

            // A classic script (not fetch/JSON) so the wiki also opens straight from disk (file://).
            string outFull = Path.GetFullPath(outPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outFull)!);
            using (var file = new StreamWriter(outFull, false, new UTF8Encoding(false)))
            {
                file.Write("// Generated by: AsperetaWeb wiki. Do not edit; run build-wiki.bat again instead.\n");
                file.Write("window.ASPERETA_WIKI = ");
                file.Write(Encoding.UTF8.GetString(buffer.ToArray()));
                file.Write(";\n");
            }

            Console.WriteLine($"Wrote {outFull} ({new FileInfo(outFull).Length / 1024} KB)");

            // Pictures: the converted client assets' frame index as a script too (file:// again).
            string wikiDir = Path.GetDirectoryName(outFull)!;
            string indexJson = Path.Combine(assetsDir, "index.json");
            string assetsScript = Path.Combine(wikiDir, "assets-index.js");
            if (File.Exists(indexJson))
            {
                WriteScript(assetsScript, "ASPERETA_ASSETS", File.ReadAllText(indexJson, Encoding.UTF8));
                Console.WriteLine($"Wrote {assetsScript} (pictures from {Path.GetFullPath(assetsDir)})");
            }
            else
            {
                if (File.Exists(assetsScript)) File.Delete(assetsScript);
                Console.WriteLine($"No {Path.GetFullPath(indexJson)}: the wiki will have no pictures. Run convert-assets.bat first to add them.");
            }

            if (!string.IsNullOrEmpty(singlePath)) WriteSingleFile(wikiDir, assetsDir, singlePath);
            return 0;
        }

        private static void WriteScript(string path, string variable, string json)
        {
            using var file = new StreamWriter(path, false, new UTF8Encoding(false));
            file.Write("// Generated by: AsperetaWeb wiki. Do not edit; run build-wiki.bat again instead.\n");
            file.Write("window." + variable + " = ");
            file.Write(json.Trim());
            file.Write(";\n");
        }

        /// <summary>
        /// The whole wiki as one HTML file to download or share: page, styles, scripts, data,
        /// frame index and every sprite sheet (as data: URIs) inlined.
        /// </summary>
        private static void WriteSingleFile(string wikiDir, string assetsDir, string singlePath)
        {
            string Read(string name) => File.ReadAllText(Path.Combine(wikiDir, name), Encoding.UTF8);
            // Keeps "</script" inside the inlined code from closing the tag early.
            string Inline(string code) => "<script>\n" + code.Replace("</script", "<\\/script", StringComparison.OrdinalIgnoreCase) + "\n</script>";

            string html = Read("index.html");
            html = html.Replace("<link rel=\"stylesheet\" href=\"wiki.css\">", "<style>\n" + Read("wiki.css") + "\n</style>");
            html = html.Replace("<a class=\"play\" href=\"../index.html\">Play</a>", "");

            var sheets = new StringBuilder("window.ASPERETA_SHEETS = {");
            string gfx = Path.Combine(assetsDir, "gfx");
            int count = 0;
            if (Directory.Exists(gfx) && File.Exists(Path.Combine(wikiDir, "assets-index.js")))
            {
                foreach (string png in Directory.GetFiles(gfx, "*.png").OrderBy(f => f, StringComparer.Ordinal))
                {
                    if (count++ > 0) sheets.Append(',');
                    sheets.Append('"').Append(Path.GetFileNameWithoutExtension(png)).Append("\":\"data:image/png;base64,")
                          .Append(Convert.ToBase64String(File.ReadAllBytes(png))).Append('"');
                }
            }
            sheets.Append("};");

            foreach (string name in new[] { "data.js", "assets-index.js", "wiki-model.js", "wiki.js" })
            {
                string tag = name == "assets-index.js"
                    ? "<script src=\"assets-index.js\" onerror=\"void 0\"></script>"
                    : $"<script src=\"{name}\"></script>";
                string code = name == "assets-index.js"
                    ? (File.Exists(Path.Combine(wikiDir, name)) ? Read(name) + "\n" + sheets : "")
                    : Read(name);
                if (!html.Contains(tag)) throw new InvalidOperationException($"index.html no longer loads {name}; update WikiExporter.WriteSingleFile.");
                html = html.Replace(tag, Inline(code));
            }

            string full = Path.GetFullPath(singlePath);
            Directory.CreateDirectory(Path.GetDirectoryName(full)!);
            File.WriteAllText(full, html, new UTF8Encoding(false));
            Console.WriteLine($"Wrote {full} ({new FileInfo(full).Length / 1024} KB, {count} sprite sheets inlined)");
        }

        private static void WriteValue(Utf8JsonWriter json, object value)
        {
            switch (value)
            {
                case null:
                case DBNull:
                    json.WriteNullValue();
                    break;
                case long l: json.WriteNumberValue(l); break;
                case int i: json.WriteNumberValue(i); break;
                case short s: json.WriteNumberValue(s); break;
                case byte b: json.WriteNumberValue(b); break;
                case bool b: json.WriteNumberValue(b ? 1 : 0); break;
                case double d:
                    if (double.IsFinite(d)) json.WriteNumberValue(d); else json.WriteNullValue();
                    break;
                case float f:
                    if (float.IsFinite(f)) json.WriteNumberValue(f); else json.WriteNullValue();
                    break;
                case decimal m: json.WriteNumberValue(m); break;
                case byte[]:
                    json.WriteNullValue();
                    break;
                default:
                    json.WriteStringValue(Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture));
                    break;
            }
        }
    }
}
